name: Stabelo Node.js package CI

on: push
    
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: [self-hosted, ci]

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.stabelo.net
    - run: npm ci
    - run: npm run format -- --check
    - run: npm run lint
    - run: npm run build
    - run: npm test
  publish:
    needs: build
    
    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: [self-hosted, ci]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: 14.x
        registry-url: https://npm.stabelo.net
    - run: npm ci
    - run: npm run build
    - run: npm publish
